import { create } from "zustand";

export const useTransactionHistoryStore = create((set) => ({
  transactions: [
    {
      key: 0,
      name: "T-Shirt (Navy Blue)",
      category: "Clothes",
      date: "28/05/2023, 12:23:36 am",
      status: "PENDING EVALUATION - CASH IN",
      colour: ["orange.600", "orange.400"],
      value: 4,
    },
    {
      key: 1,
      name: "Rice Cooker",
      category: "Home Appliances",
      date: "28/05/2023, 12:20:36 am",
      status: "ITEM PURCHASED - CASH OUT",
      colour: ["blue.600", "blue.400"],
      value: 25,
    },
    {
      key: 2,
      name: "Glass Bottles x25",
      category: "Glass",
      date: "20/05/2023, 11:23:36 am",
      status: "APPROVED - CASH IN",
      colour: ["green.600", "green.400"],
      value: 5.6,
    },
    {
      key: 3,
      name: "Newspapers x10",
      category: "Mix Paper",
      date: "10/05/2023, 12:19:36 am",
      status: "REJECTED - CASH IN",
      colour: ["red.600", "red.400"],
      value: 2.2,
    },
    {
      key: 4,
      name: "Plastic Bottles x5",
      category: "Plastic",
      date: "10/05/2023, 12:18:36 am",
      status: "APPROVED - CASH IN",
      colour: ["green.600", "green.400"],
      value: 1.1,
    },
    {
      key: 5,
      name: "Plastic Bottles x2",
      category: "Plastic",
      date: "10/05/2023, 12:20:36 am",
      status: "APPROVED - CASH IN",
      colour: ["green.600", "green.400"],
      value: 0.7,
    },
  ],
  setTransactions: (transactions) => set({ transactions: transactions }),
}));
